$:.unshift(File.dirname(__FILE__))
require 'matchers/collection_equality_matchers'
require 'matchers/all_matchers'
require 'matchers/detector_matchers'
require 'matchers/change_matchers'
require 'matchers/containment_matchers'
require 'matchers/definition_matchers'
require 'matchers/delta_matchers'
require 'matchers/subclass_matchers'
require 'matchers/tolerance_matchers'
